CREATE TABLE IF NOT EXISTS receiving_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pr_id INT NOT NULL,
  po_id INT DEFAULT NULL,
  doc_no VARCHAR(50) DEFAULT NULL,
  received_by INT DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pr_id) REFERENCES pr(id) ON DELETE CASCADE,
  FOREIGN KEY (po_id) REFERENCES po(id) ON DELETE SET NULL,
  FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS receiving_report_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  receiving_id INT NOT NULL,
  pr_item_id INT DEFAULT NULL,
  po_item_id INT DEFAULT NULL,
  item_desc TEXT DEFAULT NULL,
  item_unit VARCHAR(50) DEFAULT NULL,
  ordered_qty DECIMAL(15,2) DEFAULT 0,
  received_qty DECIMAL(15,2) DEFAULT 0,
  diff_qty DECIMAL(15,2) DEFAULT 0,
  reason TEXT DEFAULT NULL,
  FOREIGN KEY (receiving_id) REFERENCES receiving_reports(id) ON DELETE CASCADE,
  FOREIGN KEY (pr_item_id) REFERENCES pr_items(id) ON DELETE SET NULL,
  FOREIGN KEY (po_item_id) REFERENCES po_items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
